#! /bin/bash

MODEL="AMBER"

PACK_PATH=$(rospack find amber_sim)
MDL_PATH="$PACK_PATH/urdf/amber.xacro"

rosservice call gazebo/delete_model "{model_name: '$MODEL'}"

rosparam set robot_description "$(xacro $MDL_PATH)"

rosrun gazebo_ros spawn_model -urdf -model $MODEL -param robot_description